# Generated by Django 4.1 on 2024-07-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "avatar",
                    models.ImageField(
                        help_text="最佳尺寸：500x755", upload_to="slide", verbose_name="头像"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("title", models.CharField(max_length=100, verbose_name="职务")),
                ("rank", models.IntegerField(verbose_name="排序")),
            ],
            options={
                "verbose_name": "团队管理",
                "verbose_name_plural": "团队管理",
                "db_table": "team",
            },
        ),
    ]
