# Generated by Django 4.1 on 2024-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(
                help_text="最佳尺寸：500x755", upload_to="item", verbose_name="头像"
            ),
        ),
    ]
