# Generated by Django 4.1 on 2024-07-28 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slide", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="slide",
            table="slide",
        ),
    ]
